//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace приложение
{
    using System;
    using System.Collections.Generic;
    
    public partial class spt_fallback_db
    {
        public string xserver_name { get; set; }
        public System.DateTime xdttm_ins { get; set; }
        public System.DateTime xdttm_last_ins_upd { get; set; }
        public Nullable<short> xfallback_dbid { get; set; }
        public string name { get; set; }
        public short dbid { get; set; }
        public short status { get; set; }
        public short version { get; set; }
    }
}
