//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace приложение
{
    using System;
    using System.Collections.Generic;
    
    public partial class spt_fallback_usg
    {
        public string xserver_name { get; set; }
        public System.DateTime xdttm_ins { get; set; }
        public System.DateTime xdttm_last_ins_upd { get; set; }
        public Nullable<int> xfallback_vstart { get; set; }
        public short dbid { get; set; }
        public int segmap { get; set; }
        public int lstart { get; set; }
        public int sizepg { get; set; }
        public int vstart { get; set; }
    }
}
